apiVersion: v1
kind: Service
metadata:
  name: cell-app
  namespace: cell-{{ .Values.cellId }}
spec:
  selector:
    app: cell-app
    cell-id: "{{ .Values.cellId }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
