apiVersion: v1
kind: Secret
metadata:
  name: cell-db-secret
  namespace: cell-{{ .Values.cellId }}
type: Opaque
stringData:
  username: {{ .Values.db.user | quote }}
  password: {{ .Values.db.password | quote }}
